#ENC[AES256_GCM,data:38qsIA1tU+iQ0RsI7gjhmCbGC7/iXqwDpEZUtp2gkx0SetFkeP3iv45r9lnmJsnR9da0SKXcFFJbkDEBeOyf64Pv4bSDcZU=,iv:B4xluXTlvqB9tNPdNv67tXxbgc0QL3dBgJP6fXumb1k=,tag:4mLdzxp/HGW82/GTaJewfQ==,type:comment]
#ENC[AES256_GCM,data:TBKS4ouyYz5VujlZu4uxRW2jVN7z9uMDeb8XK/3bncC/jQg15QQcswwtyPyM/72T6WiaEd59Znlx+IIxkoOQhQv761UpAJyu99FcckTSU5BM00GB7g==,iv:HotwPgfGd0Pv5MLk5Q4hJn7Y2L/2k54xSQ47rPRHM2o=,tag:Y0s1Wq0qz2WrITOw0Rrmnw==,type:comment]
#ENC[AES256_GCM,data:y9K6iXlLlOapx26nD5lXPxIC1zPq4sqCiQeDfTbeZlCSAlYZ3BcGd4iD5uITsT6zl6L3n9W2XoPJzho/IZZW5KUMy9mPIxz/98hYGorO,iv:wu7HHtV7Jx2emKHD8US0rggTfOSeVDF1+I7rcMcOy5Q=,tag:msC4Krv8qMD1S0vomncFBw==,type:comment]
#
#ENC[AES256_GCM,data:q7CTJwO32MpMUZseMfrmzk67591LhXcbVUU+sY2ISFFGryU/UsqD4hJti2ulM18jd4PCurvHOQDSrN8bFq1XkSv3yfb6H8dVNgmNfnkphAshVucYAKhpq3YpOtOhpH+0AUc=,iv:LbmctpSLiaWn/DEdjaPWkiqipQrBN5MHUJbueW+Jiio=,tag:vy+eKr5YxHBlM99sa9CLWA==,type:comment]
#
#ENC[AES256_GCM,data:GCh3GVX6UElfzF7GL/Xvncxqixp7A07qffOPcOxYT04WeOuKS516HPCf7OMPYONExcrY5PEU+mfGMuevzw==,iv:knp60AXd0VEBjMnfINXb652VReaT9dI10ZewFaZsGVg=,tag:8JGhUHP3Y9XYNNJNwDWUcg==,type:comment]
#ENC[AES256_GCM,data:cYNnFTDQtNcySsDeSiroMw9NuESyXckexECgYkZmtl3xM4Yg/mw55T9LrWP/alQ2biRGOb6lAQoiWw==,iv:aZMvGver/9qvKq7DvXBICIdups15tFte1cHGIM9EHjw=,tag:RpHd1v5dhtrIQiW9QfVZQA==,type:comment]
LUKS_PASSPHRASE: ENC[AES256_GCM,data:fiaXIwb9TUQ003KKJ3RT5bPliLE4JBehEl8wa3kIuExTh6zK9kfU4A==,iv:wYLJ4gjyutmg1UNsHUl76D/ZQntdUD9d0QAEogfBw9o=,tag:z7hhkXPYLfzxf6heb0WI4w==,type:str]
#ENC[AES256_GCM,data:gwaJDDhzKdPFQdpy,iv:lIXlESqSR+3ph5vBMn5U8SKW1XT8ON9fymPs2JgTpCg=,tag:GHWPF6hR0V6XbBgZdl5IBg==,type:comment]
KC_DB_NAME: ENC[AES256_GCM,data:MpS/s2zcBQU=,iv:aNqmG8Jgwptq0WB3fjC/CLYQN2qRh/De+nuGp+S/n+8=,tag:PU4eWqIcrIwPhBnQgoYOZA==,type:str]
KC_DB_USER: ENC[AES256_GCM,data:Ev0sZIoVCLU=,iv:l9pX6rTAFIsrNiETC0obQEvekCzFJSNLfdajUIHRJoY=,tag:s/iRB05lle6cfZXulj+Jbg==,type:str]
KC_DB_PASSWORD: ENC[AES256_GCM,data:VWea1VvHia2SkcbNMEApnjsPD1Zbcg==,iv:Uj0NYkisOKxZ4+rWN5i2eJ2zjaixQQTVDLh/S4NUOio=,tag:O+zs3HWgW14VqsDoGKXTaA==,type:str]
#ENC[AES256_GCM,data:zV3rFewd3P2cYlUgjzUZp5jzpA9nsUs=,iv:p3lYcwkKgu6VByMzGDepZFdrQemBE5t+ypjq4TTGB8U=,tag:D2Z6sOCSE454bw3Hb9sOxw==,type:comment]
KC_ADMIN_USER: ENC[AES256_GCM,data:a4znL3M=,iv:9rp52toXyfF+M94J3jPePoxy4dMkcBudFTnTAwkD5l4=,tag:TBD1xLUtn4kmYMxYT+AC9Q==,type:str]
KC_ADMIN_PASSWORD: ENC[AES256_GCM,data:9sH5oAMn7Rya5zuTlGyXhQcx7nAn2dOwpA==,iv:rZbKX7GiZf8jqctnEaCKxxIyouOpaxuBnQfcf5VW+l0=,tag:/6qnU6fUA7DamLsgsShqqA==,type:str]
KC_REALM: ENC[AES256_GCM,data:QA1y,iv:1BiUI2P/3meUQ3MigL3P82+kfDlRGeGsXMebOmT9N88=,tag:/bPGk5TtRV1C1XSTEpsCPQ==,type:str]
OIDC_AUDIENCE: ENC[AES256_GCM,data:W/ZTfGyo8w==,iv:345Mw5BiwmnVZ8c4HjKjSYA/dlcDriVHE06fazH+DWc=,tag:wyyo5Jv44EnsROdOO/0NzA==,type:str]
#ENC[AES256_GCM,data:/+6J1MMyTw==,iv:TedQC+0uKk2yR/TZu8IPPiRf+sHjUiCizIRrRzWYaLo=,tag:Mt+cfmoUoCyFqEePigtaFQ==,type:comment]
APP_DB_NAME: ENC[AES256_GCM,data:MR1T,iv:pNrNv/+XjdYH9fT0r4ReeLHMKsh+wiN4s8aJUpuqLqU=,tag:h4KOyJKYcxBjsOjoeus6pg==,type:str]
APP_DB_USER: ENC[AES256_GCM,data:7JHgxOd7iQ==,iv:VJSWWnUApYwLxTrCt/vU5EzIg9AiRfjl8jBYLfwsUWc=,tag:dCNI1aTwekEZF/eH28Y3hg==,type:str]
APP_DB_PASSWORD: ENC[AES256_GCM,data:LfeQz9i0OmZL+rmHSpb6GhcZUZfJ9IKosg==,iv:ELZMsT9HvImuV9VfMePmxXxaLPuxCWTwTy/wY+Ab1zs=,tag:5kPHTKGckyrOoRrU8yCEjQ==,type:str]
#ENC[AES256_GCM,data:vliu5A7E,iv:DlXIcSUJiDnHulw8FowaUQwP5X/A+lRyubjDz4jm410=,tag:s5pJoHzs4ROIT8VR5I+lHA==,type:comment]
MINIO_ROOT_USER: ENC[AES256_GCM,data:h67+/8PvV8Zu,iv:6Ud081HUpdk1YioxTvySwxbB/1tWoUK21l/LmcHMWhY=,tag:Oa8Vbmk8QfX8vQFYkyhUBQ==,type:str]
MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:FMKImvCUV90pwJEno7Q2tRq/o46kXgzq2NUXBaY=,iv:FPYr0+sFVe0oEYIlEuoOPXdnFImMSCKxKDYwwQQ+uzE=,tag:/DfkWYaDkmPVM/o3J8EWnQ==,type:str]
MINIO_APP_USER: ENC[AES256_GCM,data:IUvmLyBL0xvIT2s6GxZ7BnTm,iv:iN4JBF3OVX5t6yAU/EgOrCZT4sDvW0P+Itl6PRor6Ek=,tag:EsUN7KaOs2D0J9bXeYihug==,type:str]
MINIO_APP_PASSWORD: ENC[AES256_GCM,data:9w1zgKk3MLqQmfpz8N/EehVx9WlPTftWzLFTEA==,iv:6CgKr4j+d9s3sEahaFiCjerov7qXZa498XNGSpJK0tE=,tag:q/U1NXX/Ky/q9KM3ZbcJ0g==,type:str]
MINIO_BUCKET: ENC[AES256_GCM,data:D8fEZ1Ze4BzLcUE5M5U=,iv:vQg+bJZTIz4XIlYSSNVQrDR4C7yDOo0m0WdnwRpNLew=,tag:v9SOC986oWJ4osk724QYjg==,type:str]
MINIO_REGION: ENC[AES256_GCM,data:LBEYgdmmhUUDuTgv,iv:BCqwYGLR9wn5aBBFirKk76UQp4DVBjvADzDXZ6Dd2D0=,tag:F5AaBfv+UT1zH//Nd/GwNA==,type:str]
#ENC[AES256_GCM,data:9CDDkQ==,iv:J5T5AeqKV+PvlR5moMWs9WS3ppvc/+MUK+l42QuoK/E=,tag:xFxktKwg3sAkLi/IdX5fRw==,type:comment]
LLM_API_KEY: ENC[AES256_GCM,data:PaQP6sjbTite,iv:EfUztxCZyH5g8kF8wdoP5c3UuRFKMaJi9nEOec0aF7M=,tag:WjPX151ex81nQG0dSnU3WQ==,type:str]
#ENC[AES256_GCM,data:vunznddl19FnTDA7+odp+ouj4ZZEWDVSc+ybCzwtwucZc58SFOh/L/fe+Q==,iv:LmqNNHysgNqY97cx19ecprCzbkWUPm7mTAGll1aSuqk=,tag:oOfZ+FjmpeVgwOGJGBVQgQ==,type:comment]
API_IMAGE: ENC[AES256_GCM,data:lyK6tFF8wiHRaOe18tR29Vo7JAy8m86IXFr6eeYVb1qkd2T207607asam1BUwRTV4OnumrJ2,iv:KNvhvvUfjzAPvtHLcuFP1XD8sTQuLlnHPd3n6QcepWw=,tag:yS8Q6ax3GuvVeApZA1CsVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h6kr3z86vuj0dpgu7e5dj6wj9d324d0046clp3zcl82knqr5nczskvu6j8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5U3cwWWZiSjRiU2d4WTRU
            bENxSDRyb0xMcVMwakErd1VmNlhJVnVDUWdVCm40aGZvclBjL2Vkb01yMEQ5SlJp
            dFJacitXdFBzbnkwTXAraTdnL01SaWsKLS0tICtxMUZCYm8yMWtOQUZRR0pqTnN1
            UGowbjdFUVowUXhYb3hieDR5WElRZXcKwY6BwZTpWohsw8YdSYngIiuYDXA2SN8q
            nX0ZMJePHv2kNzVctHeCpoXP1uSAO4euCRqYrfO7BKCunNx8NYWEHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T17:03:01Z"
    mac: ENC[AES256_GCM,data:UHQqs4c878FZjm1FGMnYma9/4ZrEVkJSmYIZT++RwhwTLTNHXkxa+UzyBEzPcICANpUDGRISDxeEAsmkPKpEH0yVAJti4XSEhAFHx2zvZTmQq6kkhRAs/FXv1KoA7E9vGj1WNbiQ7LaASPvZd4nZc3i8EWG9ieLhHUE1OhEmxew=,iv:ai0sAwRE8Zx5f4oA/rdONn0KBaNmE3xTQEKe4ZHLt+8=,tag:TLuYie8WQR1vkraVj/f/wQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
