#ENC[AES256_GCM,data:sNTYsWImo9RIMLujmdL5+UqnnXBQmREw/fVzOTBl6dtsiIMGJ7gaIivyr+ZfbUSnOW6pV5r/mieaVshcR1cjOfwumdR0elo=,iv:DlU3DTBD/LAVdQgATK7xNeEHKHO8vhiDKahfuHoJ5ZA=,tag:RS/6SNDF7y+7OrlVl68l/g==,type:comment]
#ENC[AES256_GCM,data:DZXJ/rWijWTqzn5Wd1oyhsuLiml+9dHCwXxg6BjOLKo5DA8AhgGdwHGckzOESAYF+2HQCSUPkf+KitZ5xzj2e3nnY4pLvP8xfYiMfXM4zBftOX5Z6A==,iv:+nSujgSniVeSLLmyNpjBZBuFIRLazH4t+/ZYt6oPd5w=,tag:UFkGEbIrFkXP+fWTXDJSvQ==,type:comment]
#ENC[AES256_GCM,data:6Nl1qN63oveJIiI1KCSJt3vWZZZngh2ECuYukjyJFEIGHDqPoG6d9sXyXSqxNgoducSs9EI/DyuB87KHlluL0utqFZpGN8xe2iU3ROwD,iv:eGUCt8BIbVurAA38d5IUCErnnbANHRmeMD3hQ4rJlCk=,tag:aoSWnOvFf25NbQtQwVMytw==,type:comment]
#
#ENC[AES256_GCM,data:jaVoYghO1AXQQWzpfgywYBFdHNwrpDaMkCCEo04RilgzU8qluBqb1QAyguFzeUfumnBxuCCKkX7+qqj3Qltvo8mIEBGo9G2oF/0Yf6KO3PizvQUjG+TbGFo+Xg+HcvxRNPc=,iv:ZQ2+RLMna3SNiiAkA+/AB7r+JOIOGx54ZHKLB1zKr8o=,tag:drmnXxtIFAZORMdp5IGInw==,type:comment]
#
#ENC[AES256_GCM,data:d2nImWbahFJNQL2lio+MSwTrvZpBz+OU1fBPl/uEjHgBizlxsWcN/YTZhoYpJW60MqY7MkgoIt9EdqM6Gw==,iv:ZLwILosazQO7t3rxngXEDUArNoYMzPiBiVe15dTqMRQ=,tag:Lo50K6AwCB5dlA87w8xhVA==,type:comment]
#ENC[AES256_GCM,data:VsYAHLOZ90Zz6rCupb1EjcD3ZfO+RIBJaHJ3LURsb7TkNoxW/Y0hj/7s77tozw1zsR0j2IvmEnkqrg==,iv:AgTVI27pRGMtEFnig6rKhOGfnblhfk7NYVg2164d3Jc=,tag:Zf9ruTxp8+BfcZbPFPdGDg==,type:comment]
LUKS_PASSPHRASE: ENC[AES256_GCM,data:9IVArLcF9NXxngYWkI3JRL+/bzjJLKqL8fgK4bnB/4oVz83n7cU8jw==,iv:oSvVu3S1+mauMdVitenjZSN5vgyD8HK15amRYDrcOAI=,tag:TpCJaO2OiQVmtH8AS266tg==,type:str]
#ENC[AES256_GCM,data:Kakov2T4MAERZFL0,iv:Misg1x1x/na+ms7YF78yD8L2rhgeHllQC6tHjuOUWvw=,tag:nn/hg+DufarjF8sbNEzqXA==,type:comment]
KC_DB_NAME: ENC[AES256_GCM,data:TI+OQOLQXZc=,iv:v7CZ/PQU7NnmkuURTYt2AqlIJWgMMqR5Xn8VdP/RY3Q=,tag:zhRv47oqLTKxny8n2I0STA==,type:str]
KC_DB_USER: ENC[AES256_GCM,data:RtlIYXxs8ak=,iv:AsdG0CGm9SbPVC3j17fPHalXdX/GMwqE5hCEx+7lQnU=,tag:vtI1CDWitzQiVpFfWxLTFA==,type:str]
KC_DB_PASSWORD: ENC[AES256_GCM,data:KZmsnHNEyjQooihz8QEA6fES2xQOfw==,iv:WYx7y5fi4ipLwMTFJcVo36Hnxd4imyw1DtnV3aOlc/s=,tag:pJ2/2AJ04g1W1TW3IvEriA==,type:str]
#ENC[AES256_GCM,data:baR/MEXlLyOzldJRYaPT6VUd+noRGY0=,iv:X3R9knLRQU4tiRBwBBzUhJvCHulqYfFXr3iqhCgGesw=,tag:05U1n5sICAblh2J+DVwcLA==,type:comment]
KC_ADMIN_USER: ENC[AES256_GCM,data:Nqu6ZyI=,iv:u92P2twBWGfLT4IwUsq0yr2aO0QuJ7wHdhAtRyWD528=,tag:cLxUSQTrX/NWlx7P8CMPGA==,type:str]
KC_ADMIN_PASSWORD: ENC[AES256_GCM,data:1hRiXE41QQNB3Wqe1eUhlXJfcVUeFFtgGQ==,iv:TELHJia7xYUrdKVvm0mmenJlAFSSoD676piPf5NLsoo=,tag:6dB9AXy0vxJsrd4z3b2f+Q==,type:str]
KC_REALM: ENC[AES256_GCM,data:UtLD,iv:tzxQqYfLcM4ipAkC422gWgw5b5QaZWhGZZ1ZJNChDQQ=,tag:3rX9ycgyJXWZq3K8gSGDmQ==,type:str]
OIDC_AUDIENCE: ENC[AES256_GCM,data:kpXXjRg6Sw==,iv:M+Dsu4luqalZD9U6e3b8Ogwu8hnLG/a9zfI2IDTV51A=,tag:9uvKfgspv0a2lhpPlFfQuQ==,type:str]
#ENC[AES256_GCM,data:SVnj1z1I8A==,iv:LJyIpzRCNGPbY221PrR2YJIrOnvzSosTpYhmk+TvE+4=,tag:CJcGQ7jqRE6r1Gy8CURoFQ==,type:comment]
ADMIN_DB_USER: ENC[AES256_GCM,data:G6+uF9yyFjbs,iv:wvDOwt6uQxcdHp1WW/f7ykGaHR2nZeEf7xq3Lf0c0J0=,tag:eXT8sSw2mpW5qC3OTGcR/g==,type:str]
ADMIN_DB_PASSWORD: ENC[AES256_GCM,data:1crXayhSSAPKz/ef/RL9M4A/M9fl+OwS1igZ,iv:5mCXJCNYaxmhPXRe7M8Smg/W5/cX0E8rQ4lr2k+Ec20=,tag:n5RaqnwXT6J8nu65aAnF5Q==,type:str]
APP_DB_NAME: ENC[AES256_GCM,data:vz/h,iv:pqxante7GByOBdyMtc+yHHwqG/0KX/V0MLAMGHZHKMg=,tag:WIUlbwsRi13neXUfm4sNzQ==,type:str]
APP_DB_USER: ENC[AES256_GCM,data:BTgp4rnwrA==,iv:xqkzZwqt7Kq49MCMr2Q4HE0x6U+4xPCVMjyEK+O2xdg=,tag:H93X94RpgtETPQVFWoT0yw==,type:str]
APP_DB_PASSWORD: ENC[AES256_GCM,data:zReCtcWnLa+CPi4tdlTgIxlPJhxNB4fUvA==,iv:rawS0Oci+t7JJVeZY/eCzyTjMH1/UI+ma5FyZjACmJ0=,tag:Vi8Wv71r6o4byw3wuyUWOw==,type:str]
NATIONAL_ID_ENCRYPTION_KEY: ENC[AES256_GCM,data:PQCVmxLLr6iXR6pxiDf8Bth7ilqdPHAsZymxqof5RymYQPM83zqTmmXsv2M=,iv:HTBfha/wlUjWz2ZA8VmsgX0n+ViClAOqySmpz0yLJa4=,tag:eHIOS21hFuh2ki53USrA/A==,type:str]
#ENC[AES256_GCM,data:h9mKKn9w,iv:uIixZxOFSLeGWjq4lgzdP2MzZAhJklbt9vCIjffGwsE=,tag:KjD3frjYY4n8CxzWW1Q8Fw==,type:comment]
MINIO_ROOT_USER: ENC[AES256_GCM,data:33rn250iOkCZ,iv:BYbCcsRUuzH1k9WdEl2RehAvQpSmMfsbnMzSseEtT/U=,tag:qbeJfDtV4XQgh+XFdyuu8g==,type:str]
MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:LNDYZE8O/zDPIVNSYKSQYWy+/AjbfHeDPbbCiE0=,iv:iJvypNAczFqPOcr53MK7pnLv5HhQhipTnLP4mDE9HfE=,tag:3Rs9ImNOmg8+HgpPpiyITw==,type:str]
MINIO_APP_USER: ENC[AES256_GCM,data:jyiuoTpq9U4Zams411S2jRal,iv:M9aAaqpZ0IZ+jK4u+JIqoXiQrGdK+2+fbL44Mf44njs=,tag:oce9h2IR8K38SfPe38ECkA==,type:str]
MINIO_APP_PASSWORD: ENC[AES256_GCM,data:hWyKR95r5UpzKWez3U+CJgOGQ+/C0o/kXme9/A==,iv:zKfXenXYN03U72nCvqstQBHAMcf0zTlA/OHUgL9EWWQ=,tag:FIyGz8FmMN8goEAZAGLiuA==,type:str]
MINIO_BUCKET: ENC[AES256_GCM,data:H7UBaGsJVPfpbz1f46o=,iv:7X9YkhvaCzD+ox3rbToxhvoHue8KLZsTGoK3CUJ8gDk=,tag:rY3wGP+Kq7qauknGbmdW7Q==,type:str]
MINIO_REGION: ENC[AES256_GCM,data:OT+Gdu7M1qADFhl9,iv:74g11YzNw7cN8Q860vT1FZtRArjVNHeOJhEz/ODJWFM=,tag:Kdens3hdwGKvZo6IWlEoJQ==,type:str]
#ENC[AES256_GCM,data:XPPVY0XyZeXPUQJQ0CxPY/1YNraISR6lJ9TwR61GNthiZVcqn6O+U4398w==,iv:thMv4I9dIl7krCTv9yVHArbE4eJoIM1UDbpdEmravNk=,tag:J2tNOOExSVygZJRaZ6EEJg==,type:comment]
API_IMAGE: ENC[AES256_GCM,data:XiQ53ZjqpBVepKtZiwi+mkT/pY87KeXP7r1of2qo3rYYLEZiigr2hxQm5LR6aqNtvWCkqQjb,iv:zv96lPG/+rshO+hdFVmNb3PntEFuaniIv4thDw2LKmA=,tag:4mdzsfA+fS7zTkgZmmePtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h6kr3z86vuj0dpgu7e5dj6wj9d324d0046clp3zcl82knqr5nczskvu6j8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdDFYNXZ1d2ozYkk2SUFk
            WERIbFAvNWIyRXRrQWZUUXFxVVJzQ1pmOWhzClRyT3J3WFhwc0VEa1lPWEl1WlYr
            QkVMbU5uQ200WGgrb2lZU0RKSml5SG8KLS0tIHlJb2IyaFNYUmpwV05DSkNuTnVi
            RExJUjN5QXl2V3REL0dYUDMzU1Y4TWMKIzmYH1h+exsoqA8c4y/dHDRSdaUS9fv1
            wxEPNDUS/W64hXICgbcn1UPpLa9oiUaBgAtgepMUJUehKwnCIZUuTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T09:05:13Z"
    mac: ENC[AES256_GCM,data:34hIssQVrWa/H/tb5XipOBrnVT6HW04u7eghm2P890VNgV6TiAvfEvCpXjFPj+tdmzCKXFwYESng+tSHRpT4VWih1c2toQWZRlLe/NYK1tg4KK/ImbaDmSslJOuq4PSWhRMVOs8FWwn5EELQlsrlo6T0xlHttr2sfdBWNHY2WSU=,iv:n6L34iRbKIJAkabtOPiy8eTnNZbbPMOofHYEzs6uPIs=,tag:ZPGhuVizj2jesu/ejSapzg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
